use blogs;
-- role -- 
INSERT INTO role (`name`) VALUES ('ROLE_ADMIN'),('ROLE_USER'),('ROLE_MEMBER');

-- category--
 INSERT INTO category (`is_deleted`,`type_category`) 
 VALUES ('0','Front end');
  INSERT INTO category (`is_deleted`,`type_category`) 
 VALUES ('0','Backend');
  INSERT INTO category (`is_deleted`,`type_category`) 
 VALUES ('0','Cơ sở dữ liệu');
    INSERT INTO category (`is_deleted`,`type_category`) 
 VALUES ('0','GitHub');

-- topic --
 INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','Html','1');
  INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','Css','1');
  INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','MySql','3');
 INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','Java','2');
  INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','Javascript','1');
  INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','ReactJs','1');
  INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','GitHub','4');
 INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','PHP','2');
   INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','MongoDB','3');
   INSERT INTO topic (`is_deleted`,`name_topic`,`category_id`) 
 VALUES ('0','NextJs','1');
 
 -- user--
 INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('bao','levannhatbao29@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Bao Le','0768568963','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');
 INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('baole','levannhatbao28@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Bao Le','0768568963','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');
 INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('baonhat','levannhatbao27@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Bao Le','0768568963','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');
INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('dole','dole27@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Do Beo','0768568963','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');
INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('tunglam','tunglam27@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Tung Lam','0768568963','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');
 INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('tuan','tuan29@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Tuan Le','0768568321','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');
 INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('hai','hai28@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Hai Le','0768568123','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');
 INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('hung','hung@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Hung Le','0768678963','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');
INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('vi','vi27@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Vi Beo','0768588763','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');
INSERT INTO user (`account`,`email`,`image`,`is_deleted`,`name`,`number`,`password`,`address`) 
 VALUES ('phuong','phuong27@gmail.com','https://scontent.fdad1-1.fna.fbcdn.net/v/t39.30808-1/284180584_1458094071312347_7463131271359909719_n.jpg?stp=c7.0.40.40a_cp0_dst-jpg_p40x40&_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_ohc=WpGDAXd8M9EAX9pkjSD&_nc_ht=scontent.fdad1-1.fna&oh=00_AfDzdJ6ceaZJA36KXYN4RfinlbB6T7Nzdhi-goUB7Jvhyw&oe=65FAF645','0','Phuong','0768878963','$2a$12$yPU2ZYoEwsiy9uho55s8nu3jKtA2tYDfi/44BGcOyrgpe5MNMHlYq','33B Hoang Quoc Viet,Hue');

 
 -- blog -- 
INSERT INTO blog (`content`,`create_day`,`description`,`image_blog`,`is_deleted`,`title`,`viewer`,`category_id`,`user_id`,`topic_id`) 
VALUES('Xin các chào các bạn, khi mình đọc những bài viế trên nhóm thì mình thấy có nhiều bạn vẫn không biết đưa code lên GitHub, hoặc bị lỗi, hoặc có thể là những bạn mới và đặc biệt là các bạn không biết tạo GitHub Pages (cụ thể là hiển thị ra trang web để cho mọi người xem nhá!).','2024-03-16','Bước 1: Tạo tài khoản GitHub và download Git
Ở bước này mình để hai đường dẫn bên dưới các bạn tự thực hiện nhe.
Link GitHub: https://github.com/
Link download Git: https://git-scm.com/downloads
Bước 2: Tạo một repository mới trên Github
Sau khi các bạn đã thực hiện bước 1 xong, các bạn đăng nhập vào GitHub và tạo một repository mới để đưa code lên GitHub. Các bạn thực hiện giống như ảnh bên dưới:','https://files.fullstack.edu.vn/f8-prod/blog_posts/677/615424715714d.png','0','Cách đưa code lên GitHub và tạo GitHub Pages','500','4','2','7');
INSERT INTO blog (`content`,`create_day`,`description`,`image_blog`,`is_deleted`,`title`,`viewer`,`category_id`,`user_id`,`topic_id`) 
VALUES('Hôm nay mình có quay một video trong khóa học ReactJS là "Tạo dự án ReactJS với Webpack và Babel". Mình làm video này với mong muốn chia sẻ cho các bạn có thể hình dung ra dự án được tạo bởi "create-react-app" được xây dựng như thế nào. Các bạn có thể xem thêm video hướng dẫn ở đây nhé.','2024-03-16','1. Biên dịch code với Webpack
Tại Ternimal hãy chạy:
npm start
Lệnh này sẽ chạy webpack --mode development --watch mà ta đã cấu hình trong package.json, --watch để webpack sẽ luôn lắng nghe thay đổi, khi file thay đổi webpack sẽ thực hiện biên dịch nhé.','https://i3.ytimg.com/vi/1EBe-l1E3pM/maxresdefault.jpg','0','Tạo dự án ReactJS với Webpack và Babel','1000','1','3','6');
INSERT INTO blog (`content`,`create_day`,`description`,`image_blog`,`is_deleted`,`title`,`viewer`,`category_id`,`user_id`,`topic_id`) 
VALUES('Có bạn nào thắc mắc thẻ rel="preconnect" trong trường hợp này dùng để làm gì không?
Thì câu trả lời là nó để "kết nối trước", từ này có vẻ hơi khó hiểu nhỉ. Ok, để mình giải thích thêm cho các bạn hiểu rõ hơn','2024-03-16','Khi bạn biết mình sẽ sớm cần một tài nguyên từ 1 URL nào đó (trong trường hợp này là từ https://fonts.googleapis.com và https://fonts.gstatic.com để lấy các font), nhưng bạn chưa biết url đầy đủ của nó (url đầy đủ của nó là: https://fonts.googleapis.com/css2?family=Roboto:wght@500;700&display=swap)
Thì lúc này HTML sẽ tới trang web lấy font về cho chúng ta trước khi dòng này được gọi <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500;700&display=swap" rel="stylesheet">
Ưu điểm: Dùng cách này tốc độ lấy tài nguyên từ 1 trang web bên thứ 3 về sẽ nhanh hơn 1 tẹo
Nhược điểm: Song, có ưu thì cũng phải có nhược. Việc thiết lập và duy trì kết nối mở này rất tốn kém – cho cả máy khách và máy chủ. Vì vậy, lời khuyên của mình là các bạn chỉ nên sd cách tiếp cận này cho từ 4-6 trang web bên thứ 3 là hợp lí rồi.','https://files.fullstack.edu.vn/f8-prod/blog_posts/6782/6412fd42b7052.jpg','0','"Kết nối trước" với preconnect, prefetch để làm gì?','700','1','4','1');
INSERT INTO blog (`content`,`create_day`,`description`,`image_blog`,`is_deleted`,`title`,`viewer`,`category_id`,`user_id`,`topic_id`) 
VALUES('Trong bài viết này, tôi muốn giới thiệu các trang web khác nhau mà bạn có thể sử dụng để học JavaScript khi chơi trò chơi. Phương pháp này được gọi là game hóa và là một kỹ thuật nổi tiếng hiện nay.','2024-03-19','Thông thường, nếu bạn học một công nghệ hoặc ngôn ngữ mới, bạn có thể không giữ được động lực của mình. Điều này là do số lượng công nghệ dường như vô tận. Có thể khó tiếp tục gắn bó với công nghệ đặc biệt phức tạp và việc học bị bế tắc.
Gamification là một giải pháp tốt cho vấn đề này. Nó sử dụng một nỗ lực chiến lược đơn giản để thúc đẩy và thu hút người dùng trong khi tìm hiểu điều gì đó mới. Đó là một kỹ thuật thêm các yếu tố thiết kế điển hình từ các trò chơi để nâng cao quá trình học tập. Điều này được thực hiện bằng cách thúc đẩy mong muốn tự nhiên của mọi người về giao tiếp xã hội, học tập, làm chủ, cạnh tranh, thành tích, địa vị hoặc thể hiện bản thân. Việc triển khai sớm Gamification sử dụng một hệ thống phần thưởng đơn giản cho người chơi sau khi họ hoàn thành nhiệm vụ để thu hút họ. Phần thưởng bao gồm điểm số, huy hiệu thành tích hoặc tiền ảo để sử dụng.
+Một cách tiếp cận khác của Gamification biến đổi chính nhiệm vụ trong trò chơi. Điều này được thực hiện bằng cách bao gồm một lựa chọn có ý nghĩa, hướng dẫn giới thiệu hoặc thêm một câu chuyện.
+Trong chương tiếp theo, tôi sẽ chỉ ra các trang web khác nhau có thể được sử dụng để học JavaScript bằng cách chơi trò chơi hoặc giải câu đố.','https://files.fullstack.edu.vn/f8-prod/blog_posts/6936/6422afa5a62f8.jpg','0','Learn JavaScript while Playing Games — Gamify Your Learning','600','1','3','5');



INSERT INTO `blogs`.`favorite` (`blog_id`, `user_id`) VALUES ('1', '2');
INSERT INTO `blogs`.`favorite` (`blog_id`, `user_id`) VALUES ('2', '2');
INSERT INTO `blogs`.`favorite` (`blog_id`, `user_id`) VALUES ('3', '2');
INSERT INTO `blogs`.`favorite` (`blog_id`, `user_id`) VALUES ('4', '2');


INSERT INTO user_has_role (`user_id`,`role_id`) values (1,1),(2,2),(3,2),(4,3),(5,3),(6,1),(7,2),(8,2),(9,3),(10,3);


INSERT INTO `blogs`.`type_product` (`type_product`) VALUES ('Văn Phòng');
INSERT INTO `blogs`.`type_product` (`type_product`) VALUES ('Gamming');
INSERT INTO `blogs`.`type_product` (`type_product`) VALUES ('Có Dây');
INSERT INTO `blogs`.`type_product` (`type_product`) VALUES ('Không Dây');
INSERT INTO `blogs`.`type_product` (`type_product`) VALUES ('Set');

INSERT INTO product (name_product, description, image_product, is_deleted, content, quantity,price,type_product_id) VALUES
('Microsoft Office 365', 'Bộ ứng dụng văn phòng trực tuyến của Microsoft', 'https://example.com/office365.jpg', 0, 'Microsoft Office 365 là một bộ ứng dụng văn phòng trực tuyến hàng đầu, bao gồm Word, Excel, PowerPoint và nhiều ứng dụng khác.', 100,500000,1),
('Adobe Photoshop', 'Phần mềm chỉnh sửa ảnh chuyên nghiệp của Adobe', 'https://example.com/photoshop.jpg', 0, 'Adobe Photoshop là một phần mềm chỉnh sửa ảnh chuyên nghiệp, được sử dụng rộng rãi trong thiết kế đồ họa và nhiếp ảnh số.', 50,500000,2),
('AutoCAD', 'Phần mềm thiết kế và vẽ kỹ thuật của Autodesk', 'https://example.com/autocad.jpg', 0, 'AutoCAD là một phần mềm thiết kế và vẽ kỹ thuật hàng đầu, được sử dụng rộng rãi trong các ngành công nghiệp như xây dựng, kiến trúc và cơ khí.', 30,500000,3),
('Visual Studio Code', 'Môi trường phát triển mã nguồn mở và miễn phí của Microsoft', 'https://example.com/vscode.jpg', 0, 'Visual Studio Code là một môi trường phát triển mã nguồn mở và miễn phí, phù hợp cho phát triển web, mobile và nhiều loại ứng dụng khác.', 80,500000,4),
('VMware Workstation', 'Phần mềm ảo hóa máy tính của VMware', 'https://example.com/vmware.jpg', 0, 'VMware Workstation là một phần mềm ảo hóa máy tính mạnh mẽ, cho phép bạn chạy nhiều hệ điều hành trên cùng một máy tính.', 20,500000,5),
('Sketch', 'Phần mềm thiết kế giao diện người dùng cho Mac', 'https://example.com/sketch.jpg', 0, 'Sketch là một phần mềm thiết kế giao diện người dùng chuyên nghiệp cho các thiết kế trên nền tảng Mac.', 40,500000,1);




UPDATE `blogs`.`product` SET `content` = 'Sennheiser HD206 là chiếc tai nghe choàng đầu lý tưởng cho những ai đang tìm kiếm một sản phẩm cân bằng về thiết kế, hiệu suất và giá bán.', `description` = 'Sennheiser HD 206 có thiết kế kiểu tai nghe closed back với các miếng đệm lót tai đặt bên trong chụp tai. Các lớp đệm này rất mềm mại và ôm khít với tai để mang lại khả năng chống ồn tuyệt vời. Mỗi khi bạn nghe nhạc, xem phim hay chơi game, các âm thanh từ bên ngoài sẽ bị ngăn không cho đi vào tai.', `image_product` = 'https://images.fpt.shop/unsafe/fit-in/750x500/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/11/25/637734458601378209_3.jpg', `name_product` = 'Tai nghe chụp tai Sennheiser HD206', `price` = '335000', `quantity` = '10', `type_product_id` = '3' WHERE (`id` = '1');
UPDATE `blogs`.`product` SET `content` = 'Với thiết kế hiện đại, khả năng mang tới trải nghiệm âm thanh tốt và mức giá bán ra phải chăng, chiếc tai nghe bluetooth choàng đầu i.value A8 cho thấy mình là sự lựa chọn sáng giá đối với người tiêu dùng Việt.', `description` = 'value A8 được sản xuất từ chất liệu nhựa ABS bền bỉ và nhẹ nhàng. Phần chụp tai được thiết kế khéo léo với kích cỡ vừa đủ để ôm tai người dùng, tránh những tác động của tạp âm bên ngoài tới trải nghiệm âm thanh bên trong, chất liệu da mềm mại đảm bảo khiến bạn vừa lòng khi sử dụng.', `image_product` = 'https://images.fpt.shop/unsafe/fit-in/200x200/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2019/9/25/637050170629776514_HASP-Tainghe-iValue-A8-00602556-2.jpg', `name_product` = 'Tai nghe bluetooth chụp tai ivalue A8 có mic', `price` = '275000', `type_product_id` = '4' WHERE (`id` = '2');
UPDATE `blogs`.`product` SET `content` = 'Không chỉ đẹp với thiết kế đèn LED RGB rực rỡ, tai nghe chơi game SoundMax AH-335 còn có kiểu dáng hiện đại, đeo lâu không mệt và chất âm đỉnh cao để cung cấp một không gian giải trí riêng cho mỗi game thủ.', `description` = 'So với những thế hệ tai nghe SoundMax trước đây, SoundMax AH-335 đã được lột xác hoàn toàn trong một thiết kế trẻ trung và hiện đại hơn. Trên chiếc tai nghe chơi game này, nhà sản xuất sử dụng các đường nét góc cạnh, hầm hố và liền lạc hơn để cuốn hút bất kỳ game thủ nào ngay từ cái nhìn đầu tiên.', `image_product` = 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/9/19/638307401124435680_tai-nghe-choang-dau-co-mic-gaming-soundmax-ah335-dd-docquyen.jpg', `name_product` = 'Tai nghe choàng đầu có mic Gaming Soundmax AH335', `price` = '455000' WHERE (`id` = '3');
UPDATE `blogs`.`product` SET `content` = 'Thiết kế dạng dây đeo quanh cổ mini kết hợp với cơ chế nút nhét tai giúp tai nghe nhét tai i.value BT008 phát huy tối đa thế mạnh của kết nối không dây bluetooth, từ đó hỗ trợ người dùng hiệu quả trong quá trình chạy bộ hoặc tập thể thao, tránh gây nên cảm giác vướng víu khó chịu.', `description` = 'Tai nghe ivalue BT008 được thiết kế dây đeo quanh cổ, kết hợp với cơ chế nút nhét tai hỗ trợ người dùng trong quá trình chạy bộ hoặc tập luyện, hạn chế cảm giác vướng víu và khó chịu. Đặc biệt, với khả năng kết nối không dây từ xa, giúp bạn nghe nhạc dù ở xa thiết bị 10m vẫn không bị nhiễu sóng hay gián đoạn kết nối.', `image_product` = 'https://images.fpt.shop/unsafe/fit-in/200x200/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2019/12/17/637121958918503274_HASP-Tainghe-ivalue-BT006-RED-00630786-3.jpg', `name_product` = 'Tai nghe bluetooth ivalue BT008', `price` = '225000' WHERE (`id` = '4');
UPDATE `blogs`.`product` SET `content` = 'I.value là thương hiệu sản xuất âm thanh cực kỳ đỉnh. Các dòng tai nghe hoặc loa I.value có chất lượng âm thanh rất tốt. Ưu điểm của dòng này là giá thành rẻ hơn rất nhiều so với những hãng cùng chất lượng.', `description` = 'Tai nghe nhét tai iValue M-13 là một lựa chọn lý tưởng cho những người yêu thích âm nhạc di động. Với thiết kế nhỏ gọn và ergonomically, iValue M-13 mang lại sự thoải mái khi sử dụng trong thời gian dài. Được trang bị driver động đẩy lên đến 10mm, tai nghe này cung cấp âm thanh rõ ràng, đầy đủ và cân bằng. Chất lượng âm thanh vượt trội của iValue M-13 giúp bạn tận hưởng mọi chi tiết âm nhạc một cách sâu sắc và sống động. Với cáp dài 1.2m và jack cắm 3.5mm tiêu chuẩn, bạn có thể kết nối dễ dàng với hầu hết các thiết bị âm thanh, từ điện thoại di động đến máy tính bảng và laptop.', `image_product` = 'https://images.fpt.shop/unsafe/fit-in/200x200/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2020/4/14/637224540254050984_anh-dai-dien.jpg', `name_product` = 'Tai nghe nhét tai ivalue M-13', `price` = '150000', `type_product_id` = '3' WHERE (`id` = '5');
UPDATE `blogs`.`product` SET `content` = 'Với thời lượng pin lên đến 40 giờ, Beats Solo3 sẽ trở thành chiếc tai nghe bluetooth hoàn hảo cho bạn tận hưởng những âm thanh tuyệt vời mỗi ngày. Thiết kế thông minh của sản phẩm đảm bảo nó vừa vặn với mọi kích cỡ tai và cung cấp trải nghiệm đeo thoải mái cả ngày.', `description` = 'Tổng Quan. Với thời lượng pin lên tới 40 giờ, Beats Solo3 Wireless là chiếc tai nghe hoàn hảo để đeo hàng ngày. Với công nghệ sạc nhanh Fast Fuel, bạn chỉ cần sạc 5 phút là có 3 giờ nghe. Bạn có thể thưởng thức âm thanh Beats từng đoạt giải thưởng và thoải mái nghe nhạc không dây bằng công nghệ Bluetooth loại 1.', `image_product` = 'https://images.fpt.shop/unsafe/fit-in/200x200/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/4/19/637859809262689444_tai-nghe-choang-dau-beats-solo3-wireless-hong-dd.jpg', `name_product` = 'Tai nghe chụp tai Beats Solo3 Wireless', `price` = '4290000', `type_product_id` = '4' WHERE (`id` = '6');
INSERT INTO `blogs`.`product` (`id`, `content`, `description`, `image_product`, `is_deleted`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('7', 'Thiết kế mới theo hình dạng của tai, đem lại cảm giác thoải mái khi sử dụng thời gian dài. Kết nối với thiết bị qua jack cắm 3.5mm', 'Tai nghe Earpods with Remote and Mic với thiết kế tinh tế và thời trang cùng chất lượng âm thanh vượt trội, chắc chắn chiếc tai nghe Earpods với Remote và Mic MD827ZM/A sẽ đánh bật tất cả các sản phẩm tai nghe khác và trở thành sự lựa chọn hoàn hảo để xứng đôi với những những thiết bị di động cao cấp của bạn.', 'https://images.fpt.shop/unsafe/fit-in/200x200/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2016/8/26/636078309815778221_HMPK-TAI-NGHE-EARPODS-WITH-REMOTE-AND-MIC-MD827ZMA-0001471.png', '0', 'Tai nghe EarPods with 3.5 mm Headphone Plug', '549000', '20', '4');
INSERT INTO `blogs`.`product` (`id`, `content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('8', 'Marshall Major IV là phiên bản cải tiến của tai nghe không dây Marshall Major III. Sản phẩm mang đến nhiều tính năng đáng chú ý và cải thiện rõ rệt so với thế hệ trước.', 'Marshall Major IV có thời lượng pin lâu dài lên đến 80 giờ và sạc không dây. Ngoài ra, chúng còn có thiết kế ergonomic được cải tiến, các driver động đặc biệt được tinh chỉnh và chất lượng âm thanh nổi bật với bass mạnh, giữa trơn và treble sáng. Chỉ với 15 phút sạc, bạn có thể thưởng thức 15 giờ nghe nhạc.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/4/14/638170796448977150_00872260-ava.jpg', 'Tai nghe Bluetooth choàng đầu Marshall Major IV', '3890000', '20', '4');
INSERT INTO `blogs`.`product` (`id`, `content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('9', 'Không chỉ có màu sắc độc đáo theo phong cách camo, tai nghe chơi game Corsair HS60 Haptic còn cung cấp trải nghiệm đeo thoải mái, âm trầm sâu và micro tích hợp tiện lợi.', 'TÍNH NĂNG. Âm thanh tai nghe Corsair HS60 rất trong trẻo với màng loa dài 50mm, Corsair HS60 cung cấp chất lượng âm thanh gần như tốt nhất trong mức giá 2 triệu đồng. Độ chính xác, âm trường đều được tái hiện tốt. Trải nghiệm trong game với âm thanh sẽ sống động và chân thực hơn rất nhiều.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/12/8/637745703274293797_avt.jpg', 'Tai nghe gaming Corsair HS60 có mic', '2650000', '15', '3');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('màn hình Xiaomi G27i EU là hàng loạt công nghệ hiển thị ấn tượng, đáp ứng tốt nhu cầu của các game thủ. Sản phẩm được trang bị tấm nền 27 inch xịn sò với tần số quét 165Hz siêu cao, đi kèm tính năng FreeSync cao cấp, có độ sâu màu 8 bit chuyên nghiệp và tốc độ phản hồi 1ms nhanh nhạy.', 'Xiaomi G27i EU được trang bị tấm nền IPS LCD rộng 27 inch với độ phân giải đạt ngưỡng Full HD (1.920 x 1.080 pixels) với khả năng hiển thị sắc nét từng chi tiết nhỏ nhất của khuôn hình. Sản phẩm có góc trông ảnh rộng 178 độ, duy trì chất lượng màu sắc không đổi ở mọi góc quan sát khác nhau.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2024/2/19/638439406181270091_man-hinh-gaming-xiaomi-g27i-eu-ela5375eu-27-inch-dd.jpg', 'Màn hình Gaming Xiaomi G27i EU-ELA5375EU/27 inch/FullHD (1920x1080)/FastIPS 165Hz', '3390000', '10', '5');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Ngồi trước không gian hiển thị của Acer Nitro VG270 E, bạn sẽ dễ dàng hòa mình vào thế giới game và phim ảnh sống động. Sản phẩm được trang bị tấm nền LCD sắc sảo rực rỡ, có độ phân giải Full HD và tần số quét 100Hz. Acer đã đưa lên chiếc màn hình này rất nhiều công nghệ hỗ trợ hiển thị ưu việt.', 'Được xây dựng hướng tới cộng đồng game thủ có yêu cầu cao về trải nghiệm hình ảnh. Màn hình Acer Nitro VG270 E gây ấn tượng với tấm nền IPS LCD rộng 27 inch với góc trông ảnh lên tới 178 độ theo cả chiều ngang và chiều dọc.', 'https://images.fpt.shop/unsafe/fit-in/200x132/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2024/1/16/638410161185772887_man-hinh-gaming-acer-nitro-vg270-e27-inch-dd.jpg', 'Màn hình Gaming Acer Nitro VG270 E/27 inch/FullHD (1920x1080)/IPS 100Hz', '2890000', '15', '5');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Mang tới trải nghiệm thân thiện và chuyên nghiệp, màn hình MSI PRO MP275 sở hữu không gian hiển thị 27 inch với tần số quét 100Hz mượt mà. Sản phẩm được trang bị công nghệ EyesErgo giúp giảm căng thẳng cho mắt để mọi phút giây học tập, giải trí, làm việc của bạn đều thật sự thoải mái.', 'Màn hình MSI Pro MP275 dễ dàng tạo ấn tượng thân thiện ngay trong lần đầu trải nghiệm. Sản phẩm được thiết kế với phong cách thanh lịch với cấu trúc chân đế công thái học, cho phép người dùng điều chỉnh độ nghiêng tấm nền sao cho phù hợp với góc quan sát.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2023/12/25/638390948210047792_man-hinh-msi-pro-mp275-27-inch-dd.jpg', 'Màn hình MSI Pro MP275/27 inch (1920x1080)/IPS 100Hz ', '2850000', '15', '5');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Samsung LC27R500FHEXXV là sản phẩm màn hình cong 27 inch từ Samsung, với các điểm nổi bật thiết kế đơn giản, độ cong tối ưu, hỗ trợ AMD Freesync cho game thủ và một mức giá bán rất dễ chịu.', 'Màn hình 27 inch Samsung LC27R500FHEXXV có độ cong 1800R tiêu chuẩn, mang đến hình ảnh chân thực và sống động hơn. Màn hình cong Samsung sẽ giúp bạn đắm chìm vào những nội dung hiển thị, làm việc tập trung hơn, giải trí thú vị hơn và thoải mái trải nghiệm mà không lo mỏi mắt.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2020/9/11/637354340891313636_man-hinh-lcd-samsung27-dd.png', 'Màn hình cong Samsung LC27R500FHEXXV/27 inch/FullHD (1920x1080)/VA 60Hz', '27500000', '20', '5');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('LG 27GQ50F-B 27 inch là mẫu màn hình hướng tới đối tượng người dùng game thủ và những ai đam mê các bộ môn eSports. Sản phẩm đạt độ phân giải Full HD, tần số quét 165Hz và tốc độ phản hồi 1ms. Công nghệ AMD FreeSync Premium giúp loại bỏ hiện tượng xé hình, giật hình.', 'Việc LG 27GQ50F-B hỗ trợ tần số quét 165Hz giúp sản phẩm có thể mô tả thao tác hình ảnh chuyển động cực kỳ mượt mà và nịnh mắt. Người chơi sẽ phản ứng nhanh hơn, nắm bắt các diễn biến trong game cực kỳ dễ dàng, đồng thời cảm nhận tiết tấu game theo cách trọn vẹn nhất. Đây là tính năng sẽ tác động trực tiếp đến trải nghiệm nhìn ngắm và chơi game trên màn hình LG.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/7/26/637944408571945984_man-hinh-lg-27gq50f-b27-inch-dd.jpg', 'Màn hình Gaming LG 27GQ50F-B/27 inch/FHD (1920x1080)/ VA 165Hz', '3490000', '20', '5');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Cung cấp trải nghiệm hình ảnh mãn nhãn với độ phân giải Full HD, tần số quét 180Hz và loạt công nghệ nổi bật như AMD FreeSync Premium, Extreme Low Motion Blur Sync, màn hình Asus AV249Q3A 24 inch sẽ giúp bạn hòa mình vào không gian giải trí ấn tượng theo cách nổi bật nhất.', 'Đạt tần số quét 180Hz, màn hình Gaming Asus AV249Q3A 24 inch có khả năng diễn đạt mượt mà mọi tiết tấu chuyển động trong khung hình để bạn không bỏ lỡ bất cứ khoảnh khắc nào trong game. Ưu thế tuyệt vời này sẽ hỗ trợ rất nhiều khi thể hiện bối cảnh trò chơi ở những dòng game như đua xe, bắn súng góc nhìn thứ nhất, thể thao tốc độ cao...', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…97872027000_man-hinh-asus-vg249q3a-24-inch-dd.jpg', 'Màn hình Gaming Asus VG249Q3A/24 inch/FHD(1920x1080)/IPS 180Hz', '3490000', '20', '5');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Nằm trong bộ sản phẩm màn hình cao cấp của Acer, VG240Y S sở hữu tấm nền LCD với khả năng hiển thị hình ảnh sắc sảo, hỗ trợ trải nghiệm giải trí tuyệt đắc lực. Sản phẩm ghi nhận mức tần số quét thuộc hàng cao nhất trên thị trường, đồng thời hội tụ loạt công nghệ ưu việt của Acer trong lĩnh vực hiển thị hình ảnh.', 'Màn hình Acer VG240Y sẽ dễ dàng tạo dựng ấn tượng cho bạn ngay từ lần đầu tiên nhìn ngắm và trải nghiệm. Sản phẩm sở hữu tấm nền rộng 23.8 inch và ghi điểm nhờ cách thu gọn viền bao quanh gần như biến mất. Chân đế chữ V tạo điểm nhấn thẩm mỹ bằng cách sử dụng sắc đỏ bắt mắt, vừa nâng đỡ tấm nền hiệu quả, vừa phô diễn nét đẹp đặc trưng của một sản phẩm đậm chất gaming.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2021/11/22/637731901449376038_man-hinh-acer-vg240y-s-23-8-inch-fhd-den-dd.jpg', 'Màn hình Gaming Acer VG240Y S/23.8 inch/FHD (1920x1080)/IPS 165Hz', '3390000', '20', '5');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Nếu bạn làm trong lĩnh vực sáng tạo nội dung và đang kiếm tìm một chiếc màn hình phù hợp để làm việc, Asus ProArt PA247CV-P 24 inch là sản phẩm sinh ra dành cho bạn. Khả năng bao phủ 100% phổ màu sRGB và 100% phổ màu Rec.709, hỗ trợ gam màu DCI-P3 là những thế mạnh giúp ProArt PA247CV-P hỗ trợ đắc lực cho dân thiết kế, đảm bảo mọi chi tiết trong khuôn hình đều hiện lên một cách chân thực.', 'Xứng danh là chiếc màn hình tuyệt vời nhất dành cho dân thiết kế, Asus ProArt PA247CV-P 24 inch đạt độ phân giải Full HD, có góc trông ảnh rộng 178 độ và đạt 100% phổ màu sRGB cũng như 100% phổ màu Rec.709. Sản phẩm hỗ trợ xuất hình DP qua USB-C và truyền tải điện 65W cho các thiết bị trên bàn làm việc.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/7/26/637944429188679291_man-hinh-asus-proart-pa247cv-p-dd.jpg', 'Màn hình đồ họa Asus ProArt PA247CV-P/23.8 inch/FHD (1920x1080)/IPS 75Hz', '5490000', '20', '5');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Là sản phẩm hội tụ hàng loạt công nghệ hiển thị hiện đại, màn hình Asus VA27EHE 27 inch sẽ đáp ứng tốt mọi nhu cầu của bạn, từ làm việc cho đến chơi game giải trí. Tấm nền IPS LCD 27 inch siêu rộng với tần số quét 75Hz và khả năng hạn chế xé hình nhờ Adapter-Sync là những điểm cộng xứng đáng để bạn cân nhắc ở chiếc màn hình này.', 'Ba viền màn hình bao quanh của Asus VA27EHE 27 inch được nhà sản xuất thiết kế khéo léo để rút gọn kích cỡ gần như biến mất. Nhờ đó, chiếc màn hình đem lại cảm nhận chuyên nghiệp hơn trên bàn làm việc của bạn, tạo điều kiện để dễ dàng ghép nối nhiều màn hình cạnh nhau, đem đến không gian làm việc rộng mở cho những ai thường phải đa nhiệm nhiều tác vụ cùng lúc.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/9/16/637989229602361514_man-hinh-asus-va24ehe-23-8-inch-dd.jpg', 'Màn hình ASUS VA27EHE/27 inch/FHD (1920 x 1080)/IPS 75Hz', '2990000', '20', '5');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Phần mềm SteelSeries Engine rất tốt. Nó cho phép bạn tùy chỉnh đèn nền, đặt macro và lưu cấu hình. Bàn phím không có bộ nhớ tích hợp, điều này khiến việc chuyển sang máy tính khác khó hơn.', 'SteelSeries Apex 3 có khả năng tương thích tốt. Nó hoạt động hoàn toàn trên Windows, nhưng Scroll Lock và Pause / Break không hoạt động trên macOS. Tất cả các phím hoạt động bình thường trên Linux, nhưng vì không có phần mềm cho nền tảng đó và không có bộ nhớ tích hợp, người dùng Linux sẽ không thể tùy chỉnh bàn phím.', '	https://images.fpt.shop/unsafe/fit-in/214x214/filt…n-phim-co-gaming-co-day-apex-3-steelseries-dd.jpg', 'Bàn phím cơ gaming có dây Apex 3 SteelSeries', '2229000', '20', '4');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Bàn phím cơ có dây iCore ICK10 tập trung vào sự bền bỉ, hiệu suất đỉnh cao, đa dạng tính năng và tính tương thích đa nền tảng, mang lại trải nghiệm tối ưu cho cả công việc và giải trí. Với nhiều tính năng nổi bật, bàn phím cơ này sẽ mang đến trải nghiệm gõ phím và chơi game tốt nhất cho người dùng.', 'Với Blue Switch - công nghệ switch đặc trưng với âm thanh clicky vui tai mỗi khi bấm, bạn có thể tận hưởng không chỉ những cú bấm chính xác mà còn là cảm cảm giác thoải mái dù có phải sử dụng bàn phím trong thời gian dài. Blue Switch còn nổi tiếng với tốc độ phản hồi phím nhanh và đáng tin cậy, do đó với iCore ICK10, bạn sẽ có thể tập trung vào công việc sáng tạo, đắm chìm trong thế giới ảo hoặc thả lỏng cơ thể với âm nhạc mà không bị gián đoạn bởi những thao tác nhập liệu không chính xác.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…52_ban-phim-co-co-day-icore-ick10-dd-docquyen.jpg', 'Bàn phím cơ có dây iCore ICK10', '675000', '20', '4');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Thiết kế TKL thân thiện với game thủ, thuận tiện sử dụng với các Game thủ thường xuyên di chuyển. Phím xuyên LED, double injection bền bỉ.', 'Phím xuyên LED, double injection bền bỉ. Với dung lượng 2.000 mAh, ZADEZ GT-015DK sẵn sàng phục vụ các Game thủ trong các cuộc Long tranh Hổ đấu trong thời gian dài. Đa dạng lựa chọn với Blue-Red-Brown, phục vụ cảm giác gõ riêng biệt của từng Game thủ. Switch OUTEMU cao cấp, bền bỉ đến 50 triệu lần.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…18/637858933453036503_HASP-Zadek-GT-015DK-avt.png', 'Bàn phím cơ không dây Gaming ZADEZ GT-015DK', '1341000', '20', '4');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Nếu bạn muốn có những phút giây chơi game đỉnh cao nhất, bàn phím cơ Corsair K60 RGB Pro SE sẽ là một thành phần không thể thiếu trong dàn PC của bạn. Với switch hàng đầu của Cherry, những thao tác của bạn sẽ luôn được thực thi một cách chính xác nhất.', 'Một trong những điểm ấn tượng nhất trên bàn phím cơ Corsair K60 RGB Pro SE chính là hệ thống đèn nền RGB sống động. Thông qua phần mềm Corsair iCUE, người dùng có thể dễ dàng điều khiển các hiệu ứng ánh sáng RGB theo ý thích hoặc đồng bộ hóa ánh sáng toàn hệ thống một cách dễ dàng (nếu bạn sử dụng các thiết bị khác của Corsair như quạt tản nhiệt, quạt...).', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…inals/2021/12/9/637746446058791957_00772790-1.jpg', 'Bàn phím cơ có dây Corsair K60 Pro SE', '2511000', '20', '4');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Bàn phím cơ Corsair K60 Pro Red LED sẽ cải thiện trải nghiệm chơi game của bạn với Viola Switch đến từ Cherry. Ngoài ra, sản phẩm còn sở hữu khung nhôm chắc chắn và đèn nền LED đỏ sống động.', 'So với nhiều mẫu bàn phím cơ cao cấp khác trên thị trường, Corsair K60 Pro Red LED không hề đắt một chút nào. Tuy vậy, chiếc bàn phím này vẫn được nhà sản xuất chăm chút kỹ lưỡng từng chi tiết ở bên ngoài.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…ds/Originals/2021/12/8/637745731057998015_avt.jpg', 'Bàn phím cơ có dây Corsair K60 PRO ', '2025000', '20', '4');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Steelseries APEX 7 TKL thuộc dòng sản phẩm bàn phím cơ APEX mới nhất đến từ Steelseries, mang trong mình kiểu dáng thiết kế gọn nhẹ và bắt mắt, switch được chính tay hãng Steelseries sản xuất có tuổi thọ lên tới 50 triệu lần nhấn và lớp vỏ nhôm có chất liệu mang tiêu chuẩn để làm nên vỏ máy bay cực kì bền bỉ,', 'Phiên bản APEX 7 TKL mà mình trên tay sẽ sử dụng Red Switch, và cảm nhận sau khoảng vài tiếng sử dụng cho cả gõ văn bản lẫn chơi game thì mình thấy phiên bản Red Switch này của Steelseries có vẻ hơi nhẹ hơn so với chiếc bàn phím dùng Cherry MX Red Switch mà mình đang sử dụng, lực phản hồi gần như là không có nên cảm giác hơi dễ bị bấm nhầm khi gõ nhanh, tuy nhiên thì hành trình phím lên xuống khá mượt mà, khung phím được làm chắc chắn nên những thao tác trong game nhanh, sử dụng nhiều phím không bị rung lắc.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…g-co-day-apex-7-tkl-red-switch-steelseries-dd.jpg', 'Bàn phím cơ gaming có dây Apex 7 TKL Red switch SteelSeries', '3790000', '20', '4');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Ngoài thiết kế dây tiện lợi, chuột gaming iCore GM03 còn được tích hợp hệ thống đèn LED RGB ấn tượng, cảm biến quang siêu nhạy, nút bấm siêu bền và các nút tiện lợi ở cạnh bên. Đáng chú ý, sản phẩm có mức giá bán vô cùng phải chăng.', 'Chuột gaming iCore GM03 sở hữu thiết kế hiện đại và đầy góc cạnh để phù hợp với không gian chơi game của bạn. Sản phẩm nổi bật với kiểu dáng đối xứng hai bên, cho phép người dùng điều khiển dễ dàng bằng cả tay trái hoặc tay phải.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…inals/2022/4/20/637860686371233655_icore-gm03.jpg', 'Chuột Gaming Có Dây iCore GM03', '499000', '20', '3');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Steelseries Aerox 3 Wireless Đạt tiêu chuẩn 80 triệu lần nhấn (bền hơn 3 lân so với các chuột gaming khác) cũng như nâng cấp về khả năng chuột bụi và nước giúp switch bền bỉ dưới mọi điều kiện sử dụng, ngăn chặn double click và cho phép bạn thực hiện những cú click chuột chuẩn xác.', 'Steelseries Aerox 3 Wireless Đạt tiêu chuẩn 80 triệu lần nhấn (bền hơn 3 lân so với các chuột gaming khác) cũng như nâng cấp về khả năng chuột bụi và nước giúp switch bền bỉ dưới mọi điều kiện sử dụng, ngăn chặn double click và cho phép bạn thực hiện những cú click chuột chuẩn xác.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…chuot-gaming-khong-day-steelseries-aerox-3-dd.jpg', 'Chuột gaming không dây Steelseries Aerox 3 Wireless', '2990000', '20', '3');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('SteelSeries trang bị công tắc chuột riêng biệt có tên Golden Micro IP54 với tuổi thọ 80 triệu lần bấm, độ bền cao hơn gấp 4 lần so với chuột chơi game khác.', 'Aerox 3 được trang bị lớp bảo vệ AquaBarrier để bảo vệ mạch bên trong khỏi khói bụi, nước, mồ hôi, lông động vật… Phiên bản không dây chỉ khác ở phần phụ kiện và mặt sau sẽ có thêm nút gạt công tắc theo 3 kiểu kết nối: Bluetooth, OFF và Wireless. Chế độ không dây của Aerox3 Wireless còn hoạt động lên đến 200 giờ.', '	https://images.fpt.shop/unsafe/fit-in/214x214/filt…13_chuot-gaming-co-day-steelseries-aerox-3-dd.jpg', 'Chuột gaming có dây Steelseries Aerox 3', '199000', '20', '3');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Giống như nhiều model chuột chơi game khác của Corsair, Harpoon RGB PRO cũng sở hữu kiểu dáng thể thao và thiết kế phù hợp cho người dùng thuận tay phải.', 'Ngay từ hình dạng của chuột cho đến chất liệu hoàn thiện, Corsair đều lựa chọn những gì tốt nhất để mang lại trải nghiệm xứng đáng cho game thủ. Các khu vực tiếp xúc với lòng bàn tay trên chuột được hãng phủ lên một lớp cao su mềm mại, chống trơn trượt và an toàn cho da.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…562_00772793-chuot-corsair-harpoon-rgb-pro-dd.jpg', 'Chuột gaming Corsair Harpoon RGB PRO', '499000', '20', '3');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Chuột gaming không dây Corsair Katar PRO được trang bị công nghệ điều khiển thiết bị không dây Corsair Slipstream. Đây là công nghệ sử dụng sóng vô tuyến 2.4GHz của Corsair với rất nhiều tính năng vượt trội hơn so với các công nghệ khác.', 'Nhờ các đầu phát và ăng ten thu nhận tín hiệu được thiết kế thông minh, Corsair Slipstream sẽ đảm bảo các thao tác mà người dùng thực hiện trên Corsair Katar PRO Wireless có độ trễ dưới 1ms, tương đương với các mẫu sản phẩm có dây thông thường. Với công nghệ không dây vô cùng đặc sắc như Corsair Slipstream, khoảng cách giữa chuột không dây và chuột có dây phục vụ các game thủ gần như bằng không.', 'https://images.fpt.shop/unsafe/fit-in/214x214/filt…_00772784-chuot-corsair-katar-pro-wireless-dd.jpg', 'Chuột gaming Corsair Katar PRO Wireless', '890000', '20', '3');
INSERT INTO `blogs`.`product` (`content`, `description`, `image_product`, `name_product`, `price`, `quantity`, `type_product_id`) VALUES ('Chuột Có Dây Rapoo N200 thiết kế đơn giản, cân đối 2 bên, phù hợp cho cả người thuận tay trái và tay phải. Khối lượng 70 g nhẹ, gọn, cầm nắm dễ chịu, điều khiển thuận tiện.', 'Sử dụng được trên nhiều bề mặt khác nhau mà không cần dùng đến tấm lót chuột chuyên dụng, tạo nên tính linh hoạt cao cho sản phẩm. Mức độ cảm biến quang học cao ngoài đảm bảo cho các hoạt động văn phòng tối ưu thì chuột máy tính còn có thể dùng để chỉnh sửa ảnh, chơi game thông thường mượt mà.', 'https://images.fpt.shop/unsafe/fit-in/200x200/filt…636772096317963039_chuot-co-day-rapoo-n200-1o.png', 'Chuột có dây Rapoo N200', '119000', '20', '3');



INSERT INTO cart (create_order, is_deleted, status, total_price, product_id, user_id,quantity) VALUES
('2024-04-03T12:51:40.791', 0, 1, 500000, 1, 2,1),
('2024-04-03T12:51:40.791', 0, 1, 800000, 2, 2,1),
('2024-04-03T12:51:40.791', 0, 1, 1200000, 3, 3,1),
('2024-04-03T12:51:40.791', 0, 1, 500000, 4, 3,1),
('2024-04-03T12:51:40.791', 0, 1, 800000, 5, 4,1),
('2024-04-03T12:51:40.791', 0, 1, 1200000, 6, 4,1);


